### ISSUE TITLE
use of pint generates traceback

### ISSUE THREAD

**Issue by rjschwei** [SUSE/Enceladus#51]
On openSUSE 13.2:

-> pint amazon servers --region us-east-1 --smt
Traceback (most recent call last):
  File "/usr/bin/pint", line 104, in <module>
    command_args['--filter'])
  File "/usr/lib/python2.7/site-packages/susepubliccloudinfoclient/infoserverrequests.py", line 259, in get_server_data
    apply_filters=command_arg_filter
  File "/usr/lib/python2.7/site-packages/susepubliccloudinfoclient/infoserverrequests.py", line 123, in __form_url
    doc_type += '.' + server_format
TypeError: unsupported operand type(s) for +=: 'bool' and 'str'

**Comment by bear454** [comment]
The URL parameter for server type was being incorrectly processed into a boolean. Resolved in v0.1.1.
